### ISSUE TITLE
Tipping Requests with additional Text don't work

### ISSUE THREAD

**Issue by anthonyliriano** [gibwork/gibwork-github-tips#1]
When requesting a tip and the text contains additional text, the tipping bot doesn't reply. The expected outcome is that the bot should reply.

```
Dummy Text, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor

@gibworkbot tip 1 @User123
```

**Comment by x676f64** [comment]
@anthonyliriano https://github.com/gibwork/gibwork-github-tips/pull/2

**Comment by codewithmide** [comment]
I am interested in resolving this issue. Could you please direct me on how to get the `GITHUB_TOKEN`required in the `env` file?

**Comment by Redfox** [comment]
> I am interested in resolving this issue. Could you please direct me on how to get the `GITHUB_TOKEN`required in the `env` file?

Hi sir, this `GITHUB_TOKEN` env is a token from github user to listen notifications, you can create one here https://github.com/settings/tokens then the bot will listen notifications from user token

**Comment by lord-dubious** [comment]
#5 
> When requesting a tip and the text contains additional text, the tipping bot doesn't reply. The expected outcome is that the bot should reply.
> 
> ```
> Dummy Text, Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor
> 
> @gibworkbot tip 1 @User123
> ```

**Comment by Brunakalline** [comment]
#6 
> @gibworkbot tip 1 @Brunakalline
> ```

**Comment by shubhiscoding** [comment]
#6 here's a potential fix,
This updated `parseCommand` function will properly extract the username and amount when the command is a tip, and it will ignore any additional text after the tip command. This should ensure that the tipping bot replies correctly even when additional text is included in the message.
please check @anthonyliriano @Redfox
