### ISSUE TITLE
Tip via Github App

### ISSUE THREAD

**Issue by anthonyliriano** [gibwork/gibwork-github-tips#9]
As a admin in a Github Organization, I should be able to invite the [Gibworkbot App](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app) to my organization.

- The app should request the least amount of privileges.
- Instead of tagging the bot, users in the Organization can use the command: 
   \tip 1 user

**Comment by Shiva953** [comment]
The github app would contain code of this repo right?

**Comment by Redfox** [comment]
> The github app would contain code of this repo right?

@Shiva953 
I think this repository should listen to github app events

**Comment by Shiva953** [comment]
> > The github app would contain code of this repo right?
> 
> @Shiva953 
> I think this repository should listen to github app events

Yeah, that seems reasonable
@anthonyliriano would you like to elaborate more on this?

**Comment by DracocardZ** [comment]
i wiil like to help
But im new

**Comment by Web3Anthony** [comment]
> > > The github app would contain code of this repo right?
> > 
> > 
> > @Shiva953
> > I think this repository should listen to github app events
> 
> Yeah, that seems reasonable @anthonyliriano would you like to elaborate more on this?

Any specific questions? This should be your traditional Github app. Like @Redfox mentioned it probably listens to events 

1 - A user within an organization types in a command
2- Bot listens to events
3- When "Tip" responds similar to how it's setup today

**Comment by Web3Anthony** [comment]
> i wiil like to help But im new

Jump on the discord any can get you off to a good start - https://discord.com/invite/G54VHkcuHS

**Comment by anthonyliriano** [comment]
> > > The github app would contain code of this repo right?
> > 
> > 
> > @Shiva953
> > I think this repository should listen to github app events
> 
> Yeah, that seems reasonable @anthonyliriano would you like to elaborate more on this?

Any specific questions? This should be your traditional Github app. Like @Redfox mentioned it probably listens to events

1 - A user within an organization types in a command
2- Bot listens to events
3- When "Tip" responds similar to how it's setup today

**Comment by anthonyliriano** [comment]
> i wiil like to help But im new

@DracocardZ Jump on Discord if you have any specific questions with getting started, we might be able to help https://discord.com/invite/G54VHkcuHS
